### ISSUE TITLE
Data source?

### ISSUE THREAD

**Issue by cael-gomes** [dadeke/alexa-skill-meu-dividendo#1]
Website scrapping? Se sim, qual?

**Comment by dadeke** [comment]
Olá @gambitrex 🙋🏻‍♂️

Todos os dados vem da UP2DATA | B3:
[https://www.b3.com.br/pt_br/market-data-e-indices/servicos-de-dados/up2data/sobre-up2data/](https://www.b3.com.br/pt_br/market-data-e-indices/servicos-de-dados/up2data/sobre-up2data/)
(Acessado em 06 de abril de 2022)

Contato Comercial
[produtosdedados@b3.com.br](mailto:produtosdedados@b3.com.br)

Suporte Técnico
[dataservices@b3.com.br](mailto:dataservices@b3.com.br)
55 11 2565-5111

Entre em contato com eles solicite acesso aos dados de **Eventos Corporativos - _Corporate_Action_**. São estes:
[https://www.b3.com.br/data/files/18/C2/64/2D/EF4A971055622897AC094EA8/Eventos%20Corporativos%20-%20Corporate_Action.zip](https://www.b3.com.br/data/files/18/C2/64/2D/EF4A971055622897AC094EA8/Eventos%20Corporativos%20-%20Corporate_Action.zip)
(Acessado em 06 de abril de 2022)

Aí dentro contém várias informações inclusive de Dividendos e de Juros s/ Capital Próprio.
